class Const:
    SCREEN_WIDTH = 441
    SCREEN_HEIGHT = 463
    SIZE_SPACE = 1
    SIZE_BLOCK = 10
    INTERSECT_BORDER_RIGHT = SCREEN_WIDTH - 2 * SIZE_SPACE - 2 * SIZE_BLOCK
    START_LEFT_BORDER = 2 * SIZE_BLOCK + 3 * SIZE_SPACE
    INTERSECT_LEFT_BORDER = SIZE_BLOCK + 2 * SIZE_SPACE
    START_RIGHT_BORDER = SCREEN_WIDTH - 3 * SIZE_BLOCK - 3 * SIZE_SPACE
    INTERSECT_UP_BORDER = 4 * SIZE_BLOCK + 5 * SIZE_SPACE
    START_DOWN_BORDER = SCREEN_HEIGHT - 3 * SIZE_BLOCK - 3 * SIZE_SPACE
    INTERSECT_DOWN_BORDER = SCREEN_HEIGHT - 2 * SIZE_BLOCK - 2 * SIZE_SPACE
    START_UP_BORDER = 6 * SIZE_SPACE + 5 * SIZE_BLOCK
    START_X_HEAD = 4 * SIZE_BLOCK + 5 * SIZE_SPACE
    START_Y_HEAD = 5 * SIZE_BLOCK + 6 * SIZE_SPACE
